#!/usr/bin/php
<?php

require_once('vendor/autoload.php');

$climate = new League\CLImate\CLImate;

if(!isset($argv[1]))
{
  $no_args = true;
}

if(in_array("--version", $argv)){
  die($climate->out('GlitchBundler v1.0'));
}



$images = json_decode(file_get_contents("/.glitch-assets"));

$url = $images["url"];

if(file_put_contents( "img.svg",file_get_contents($url))) { 
  // epic
}



$progress = $climate->progress()->total(100);

for ($i = 0; $i <= 100; $i++) {
  $progress->current($i);

  // Simulate something happening
  usleep(80000);
}

$climate->out("Done");
